# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Clean the project"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Runs the unit tests"
  lane :unit do
    gradle(task: "test")
  end

  desc "Runs the lint"
  lane :lint do
    gradle(task: "lint")
  end

  desc "Runs code static analysis"
    lane :detekt do
      gradle(task: "detekt")
    end

  desc "Runs the functional tests"
  lane :functional do
    gradle(task: "connectedAndroidTest")
  end

  desc "Builds a new release app"
  lane :build_prod do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file"=>ENV['KEYSTORE_PATH'],
        "android.injected.signing.store.password"=>ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" =>ENV['KEYSTORE_ALIAS'],
        "android.injected.signing.key.password" =>ENV['KEYSTORE_PASSPHRASE']
      }
    )
    copy_artifacts(
        artifacts: [lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]],
        target_path: ENV['APK_DESTINATION_FOLDER']
      )
  end

  desc "Submit a new beta build to Firebase App Distribution"
    lane :distribute do |options|
      if options[:group]
        build_android_app(
          task: "assemble",
          build_type: "debug"
        )

        firebase_app_distribution(
            app: "1:7372000327:android:77572190660413f55c3562",
            groups: options[:group]
        )
      else
        UI.user_error!("Missing group name!")
      end
    end

    desc "Submit a new build to Firebase App Prod Distribution"
    lane :distribute_prod do |options|
        build_prod
        firebase_app_distribution(
            app: ENV['APP_ID'],
            groups: ENV['APP_GROUP']
        )
    end
end