# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Clean the project"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Runs the unit tests"
  lane :unit do
    gradle(task: "test")
  end

  desc "Runs the lint"
  lane :lint do
    gradle(task: "lint")
  end

  desc "Runs code static analysis"
    lane :detekt do
      gradle(task: "detekt")
    end

  desc "Runs the functional tests"
  lane :functional do
    gradle(task: "connectedAndroidTest")
  end

  desc "Builds a new release app"
  lane :build_prod do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file"=>"/Users/jorgerodriguezchala/Documents/Android/keystore.jks",
        "android.injected.signing.store.password"=>'g{(J0\/1)Jv#Gz2Tc_EiO?EcvZ!BJ!Nf5-_p)n_rxP?(vK-GkY#54R%uE4WJFjq+7oc5B{',
        "android.injected.signing.key.alias" =>"untha_care",
        "android.injected.signing.key.password" =>'~7Q&jKVtu}vt4&=6FIn)GWT^pnj39~HaG4ua+#*@PyG#A7bdY{#mehEr+xSu}(f{a-ixuE'
      }
    )
  end
end