package com.untha.utils

object Constants {

    const val ROUTE_LABOUR = "ROUTE_LABOUR"
    const val CATEGORIES_ROUTES = "CATEGORIES_ROUTES"
    const val CATEGORIES_VERSION = "version"
    const val CATEGORY_PARAMETER = "category"
    const val CATEGORIES = "CATEGORIES"
    const val CLICK_ROUTE_TITLE = "Click_route_"
    const val CLICK_ROUTE_START_TITLE = "Click_start_route_route_title"
    const val SUBTITLE_NEXT_STEP = "SIGUIENTE"

    const val MAIN_ITEM_RECYCLE_VIEW = 0
    const val SIZE_OF_ACTION_BAR = 120
    const val MARGIN_TOP_PERCENTAGE = 0.01406
    const val MARGIN_BOTTOM_MIDDLE_NEXT_STEP = 2
    const val SPAN_THREE_COLUMNS = 3
    const val SPAN_TWO_COLUMNS = 2
    const val SPAN_ONE_COLUMN = 1
    const val PERCENTAGE_MAIN_HEIGHT_LAYOUT = 0.4
    const val MARGIN_WIDTH_PERCENTAGE = 0.022
    const val MAIN_VIEW = 0
    const val SMALL_VIEW = 1
    const val PERCENTAGE_SMALL_HEIGHT_LAYOUT = 0.3
    const val MARGIN_SMALL_TOP_PERCENTAGE = 0.01093
    const val REFERENCE_DENSITY = 160

    const val PERCENTAGE_SMALL_RIGHTS = 0.33
    const val PERCENTAGE_PADDING_IMAGE_RIGHTS = 6
    const val GENERIC_PERCENTAGE_PLAYER_HEADER = 0.427

    const val GENERIC_STEP_MARGIN_MULTIPLIER = 2
    const val SIZE_HEIGHT_NEXT_STEP = 0.1981
    const val SIZE_LINE_HEIGHT_NEXT_STEP = 3
    const val PERCENTAGE_PADDING_ELEMENT_NEXT_STEP_IMAGE = 15
    const val TOP_MARGIN_NEXT_STEP = 17
    const val HEIGHT_LINE_HEADER_GENERIC = 8
    const val COORDINATES_LINE_HEADER_GENERIC = 25
    const val WIDTH_IMAGE = 0.35329
    const val WIDTH_BLOCK_OF_TEXT = 0.646706
    const val SIZE_MARGIN_IMAGE = 0.103773
    const val SIZE_OF_ACTION_BAR_ROUTE = 55
    const val SIZE_ROUTE_CATEGORY = 0.4423
    const val MARGIN_TOP_PERCENTAGE_MAIN_ROUTE = 0.01937
    const val MARGIN_LATERAL_PERCENTAGE_MAIN_ROUTE = 0.035
    const val SHADOW_PADDING_SIZE = 5
    const val LABOUR_ROUTE = "labour-route"
    const val RESULT = "result"
    const val VIOLENCE_ROUTE = "violence-route"
    const val MARGIN_SINGLE_SELECTION_QUESTION = 0.049
    const val MARGIN_HEIGHT_SELECTION_QUESTION = 0.054
    const val MARGIN_HEIGHT_QUESTION = 0.17
    const val SIZE_IMAGE_PERCENTAGE_AUDIO_ROUTE = 0.094
    const val SIZE_HEIGHT_PERCENTAGE_OPTION_BUTTON = 0.09
    const val TEMPORAL_LOAD_PROGRESS_BAR = 13
    const val START_QUESTION_ROUTE_LABOUR = 4
    const val FAULT_ANSWER = "fault-answers"
    const val TEMPORAL_MARGIN_SCREEN_LABOUR_ROUTE = 12
    const val DUPLICATE_MARGIN_LATERAL = 2
    const val STYLE_ANSWER_TWO_OPTION = 2
    const val NAME_SCREEN_LABOUR_ROUTE = "DERECHOS LABORALES"
    const val NAME_SCREEN_RIGHTS = "MIS DERECHOS"
    const val NAME_SCREEN_ROUTES = "RUTAS DE AYUDA"
    const val GO_TO = "goto"
    const val GO_TO_TEST_VALUE_FOR_MULTIPLE_OPTION_QUESTION = 9
    const val MARGIN_BOTTOM_PERCENTAGE_ANSWERS_LAYOUT = 0.020
    const val MARGIN_BOTTOM_PERCENTAGE_NEXT_BUTTON = 0.034
    const val MARGIN_TOP_AND_BOTTOM_PERCENTAGE_AUDIO_BUTTON = 0.0361
    const val HEIGHT_MULTIPLE_OPTION_PERCENTAGE = 0.10
    const val MARGIN_LEFT_RIGHT_MULTIPLE_OPTION_SCREEN_PERCENTAGE = 0.0241
    const val HALF_SCREEN_WEIGHT = 0.5F
    const val FULL_SCREEN_WEIGHT = 1F

}
